services:
  smart_palletizer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_palletizer
    environment:
      ROS_DOMAIN_ID: 0
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: 1
    volumes:
      - ./data/smart_palletizing_data_ros2/:/smart_palletizer/data/smart_palletizing_data_ros2/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    privileged: true